### ISSUE TITLE
Unable to set up platform on HA 0.103.6

### ISSUE THREAD

**Issue by snicker** [rsnodgrass/hass-flo-water#5]
I'm on `master`

```
2020-02-16 00:59:16 WARNING (SyncWorker_8) [custom_components.flo.sensor] No startdate specified. Use 2020-01-01 instead.
2020-02-16 00:59:16 WARNING (SyncWorker_13) [custom_components.flo.sensor] No startdate specified. Use 2020-01-01 instead.
2020-02-16 00:59:16 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform flo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/flo/sensor.py", line 70, in setup_platform
    sensors.append( FloPressureSensor(hass, device_id) )
  File "/home/homeassistant/.homeassistant/custom_components/flo/sensor.py", line 143, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/flo/sensor.py", line 162, in update
    if self._state != round(state, 2):
TypeError: type NoneType doesn't define __round__ method
2020-02-16 00:59:17 ERROR (SyncWorker_13) [custom_components.flo.sensor] Bad request: 2020-01-01 00:00:00+00:00:2020-02-16 00:59:16.783344+00:00:1m
```

**Comment by rsnodgrass** [comment]
Try updating to the latest master. It should resolve this issue.

**Comment by snicker** [comment]
this will still throw an error on line 163 as `state` will be `None`. `get_telemetry('psi')` is returning `None` and then the code is trying to `round` that

**Comment by snicker** [comment]
the PR above seems to be working. However, I still have a very strange issue where I don't get any data from the Flo *unless* I have the iOS app open on my phone simultaneously. Should I open an issue in the main `pyflowater` repo?

**Comment by shaz57** [comment]
i have the same issue, i only get the data first time when i restart HA, after that no data fulled from Flo.
i was using 0.0.1 with out any issue for over 4 months. 2.0.x (5/6) both had the same issue.

now if i move back to 0.0.1, i get another problem it worked first time, all zero in 2nd pull works again in 3rd pull all zero in 4th pull and and so on

see the image you can see the zero values

https://ibb.co/R9NMX72

**Comment by rsnodgrass** [comment]
Same issue everyone else has, it doesn't update unless app is open. With
Flo's change to 2.0, there must be an API that needs to be called to
trigger updates of cached state on the Flo server side. I don't have time
to dig into this right now, hopefully someone can investigate and submit a
patch.
